### ISSUE TITLE
Project does not have a LICENSE file

### ISSUE THREAD

**Issue by siddhesh** [vkrasnov/bench_lua#2]
Hi,
The project currently does not have a license file because of which it is unclear what the usage restrictions for the software are.  I have forked (and submitted a PR) in good faith under the assumption that it would eventually have an OSI-approved FOSS license but please clarify if that is not the case.

**Comment by vkrasnov** [comment]
This is definitely an open source thing. Just didn’t look important enough to add a license.

**Comment by siddhesh** [comment]
Thank you for confirming!  The benchmarks are definitely useful, thank you for writing them.  We are considering adding the benchmark to our CI for measuring luajit performance at https://ci.linaro.org/ and without a license the usage restrictions are not clear.

**Comment by vkrasnov** [comment]
Which license would you prefer?

**Comment by siddhesh** [comment]
I don't have a strong preference TBH.  Maybe given that LuaJIT itself is under an MIT license, it may be appropriate to just use that or a more permissive BSD style license.

**Comment by vkrasnov** [comment]
Done
